[package]
name = "ipc"
description = "Collection of all IPC related modules"
version = "0.0.1"
license = "MIT OR Apache-2.0"
authors = ["ConsensusLab", "Protocol Labs", "Filecoin Core Devs"]
edition = "2018"
repository = "https://github.com/consensus-shipyard/ipc-gateway"
keywords = ["filecoin", "web3", "wasm"]

[workspace]
members = [
    "gateway",
    "subnet-actor"
]

[build-dependencies]
wasm-builder = "3.0.1"